### ISSUE TITLE
Accessing request.POST modifyed body

### ISSUE THREAD

**Issue by wichert** [Pylons/webob#149]
I have a request which is POSTing JSON data, but some clients do not send along a `Content-Type` header. When this happens accessing `request.POST` will mangle the request body. Here is an example:

```python
(Pdb) p request.content_type
''
(Pdb) p request.body
'{"password": "last centurion", "email": "rory@wiggy.net"}'
(Pdb) p request.POST
MultiDict([('{"password": "last centurion", "email": "rory@wiggy.net"}', '******')])
(Pdb) p request.body
'%7B%22password%22%3A+%22last+centurion%22%2C+%22email%22%3A+%22rory%40wiggy.net%22%7D='
```

**Comment by cdevienne** [comment]
It would be interesting to know why this body rewrite is done.
Even for form data, I don't see the actual reason.

@mcdonc, @maluke, do you thing we could could remove this body rewrite ?

**Comment by bertjwregeer** [comment]
The reason for the rewrite is to allow future requests for `req.body` to still read/seek into the body. This is only really beneficial if the original `body_file` is not seekable, and thus can't be reset.

WebOb also attempts to store the result of the variables, so that the next time a user calls `req.POST` they get a cached object back, unless of course `body_file` has changed underneath it, and thus it needs to re-parse.

Those variables after parsing are thrown into `FakeCGIBody` and the `content_type` for the request according to `FakeCGIBody` is set to `application/x-www-form-urlencoded`. Upon reading from `FakeCGIBody` it will URL encode the multidict, which makes things go all screwy.
