### ISSUE TITLE
Response object adding default_content_type is perhaps bad magic

### ISSUE THREAD

**Issue by cdent** [Pylons/webob#205]
If a response is 304 or 204 or any of the other varieties with no body, then there should be no `content-type` header. WebOb doesn't respect this and instead will set the header to the value of `Response.default_content_type`.

Obviously this can be worked around in the code that uses `Response` (by setting a different default) however it seems that the default default behavior is incorrect.

Would it make sense to check `status` before choosing to use the `default_content_type`?

**Comment by cdent** [comment]
[Related openstack keystonemiddleware bug](https://bugs.launchpad.net/keystonemiddleware/+bug/1466499)

**Comment by bertjwregeer** [comment]
Yeah, this is a known issue. There are a couple of bugs reports in Pyramid that are related. 

Here's a couple of related issues:

https://github.com/Pylons/webob/issues/204
https://github.com/Pylons/webob/issues/130
https://github.com/Pylons/webob/issues/112

**Comment by bertjwregeer** [comment]
@cdent I have pushed a change that should solve this issue, please see #261, but specifically commit https://github.com/Pylons/webob/commit/a35a117131154822bc2121a44c2fdfad48d6c3d7.

This should solve the problem, I would be interested in hearing your feedback. There are a lot of other changes going into 1.7 as well, so test runs on the OpenStack could would be appreciated :-).

**Comment by cdent** [comment]
Cool. I'll give that branch a try against some stuff and report back. Looking at the specific commit those changes make sense. The only thing I'd wonder about is those situations where someone sets a response code that shouldn't have a body but also happens to set a body anyway. What happens then?

**Comment by cdent** [comment]
I've tried the branch in a couple different projects that are using webob and thus far the only non-issue has been what I've commented on #261. So lgtm.

**Comment by bertjwregeer** [comment]
If you have a body on a response that shouldn't have a body, WebOb will happily send it away.

I'm considering adding new internal only API that allows a `Response()` object to be created without doing any of the existing magic that happens for adding defaults iff it is being called from `Request.get_response()` so that we don't have to worry about this or any future side-effects when we really want the Response to look like what the user actually got returned from the application.

**Comment by bertjwregeer** [comment]
I was going back over the original code before all my changes in #261, and I noticed that it was checking to see if the `headerlist` was already supplied, and if so it wouldn't add the default Content-Type.

The check was using: `not headerlist` though, and if the list is empty, that returns `True`. I've now fixed this in:

https://github.com/Pylons/webob/pull/261/commits/fb1a2ff15f6293497e6cb63912c7627b4a01996e

So that it checks that the headerlist was `None`, i.e. not provided by the caller, and only then will it set the Content-Type to the default. This fixes it in an even cleaner way and matches what `Request.get_response()` is much better.

Also means that after WebOb 1.7 OpenStack can pull some hacks whereby it sets default_content_type to None back out of the code base.

Tests to make sure this doesn't regress have been added in this commit:

https://github.com/Pylons/webob/pull/261/commits/160326a76e0742e01e4fb7f1f73e977b1df12c11
