### ISSUE TITLE
URL is encoded automatically

### ISSUE THREAD

**Issue by vinaybond** [Pylons/webob#265]
I am using roborframework-httplibrary which internally uses webtest and webob. During my test I found that the URL is automatically getting encoded.

After some troubleshooting, I found that in **webob/request.py**, there is a methods "blank" which contains line like this:
`obj = cls(env, **kw)
`
URL is encoded by that cls. Not sure what that cls() method does. 

Any help is appreciated here.

**Comment by bertjwregeer** [comment]
Could you please provide some sample code so that I can understand the issue? Preferably just a reproduction that uses just WebOb.

`blank()` creates a new `Request` object. The `cls` is passed in as the first parameter on `blank()` because it is a `classmethod`.

URL's are required to be encoded if they contain non `latin-1` characters as they are invalid.

**Comment by vinaybond** [comment]
It is written in robotframework. Which simple hit a get request which hits this URL with headers (content/type: application/json).
 
`http://192.168.1.5/myapi/component/persn000000000001045:(itemList)`

It converts it into this when I see it using wire shark

`http://192.168.1.5/myapi/component/persn000000000001045:%28itemList%29
`

Is this URL supposed to be encoded by default? If yes, then we can close this ticket I guess.

**Comment by bertjwregeer** [comment]
Those are listed in the `reserved` list in the RFC. Python's `urllib.quote` is used internally to url quote the URL, and the defaults are used.

At this point it is expected behaviour. Your server on the receiving end should url unquote it, and pass it to your application.
