### ISSUE TITLE
performance issues in webob.exc

### ISSUE THREAD

**Issue by faassen** [Pylons/webob#282]
I'd like to draw your attention to the following issue:

https://github.com/morepath/morepath/issues/494

My impression is that there is some kind of leak in ``webob.exc.lazify`` which causes it to take increasing time each time it gets called, and when this goes up, it starts to totally dominate performance.

**Comment by bertjwregeer** [comment]
`lazify` was added so that if a template didn't use the value in the error response it wouldn't attempt to turn it into a string that may cause crashes because it is trying to access values that are tied to dead DB transactions and others:

https://github.com/Pylons/webob/pull/139

I don't see how `lazify` would be causing a memory leak, it captures the function, and returns a class. That class stores a variable, and until it's `__str__` function is called won't call the captured function.

I'd be willing to accept a patch that fixes the issue with the current `lazify`.

**Comment by bertjwregeer** [comment]
Potentially:

```
class lazify(object):
    def __init__(self, func):
        self.func = func
        self.value = None
    def __call__(self, value):
        self.value = value
    def __str__(self):
        return self.func(self.value)
```

Maybe? This way there is no class/object that is created on the fly. I'd be interested in seeing tests...
