### ISSUE TITLE
WebOb 1.7 broke text responses without charset

### ISSUE THREAD

**Issue by hyperknot** [Pylons/webob#304]
Doing a deploy in my Pyramid based app broke my generated file download responses. It turned out the reason was a silent upgrade of WebOb to 1.7, which somehow broke the default_charset support.

My problematic view had the the following:

```
body = json.dumps(map_obj.geojson, ensure_ascii=False)

return Response(content_type='application/vnd.geo+json',
           content_disposition=u'attachment; filename="{}.geojson"'.format(basename),
           body=body)
```

It gave `TypeError: You cannot set the body to a text value without a charset` for every request to this view.

Now, after Googling this error I found out it's in WebOb, so I've added WebOb<1.7 dependency to my requirements, which solved this problem for me. The alternative would have been to add charset='UTF-8' to all my responses.

But the big problem here I believe is that an unpinned package was silently upgraded mid Pyramid's release cycle, which possibly broke many production systems (or will brake in the next weeks, as most people didn't deploy during holidays).

Since I trust Pyramid to handle it's dependencies without manual pinning on my side, I believe it should definitely keep extremely important dependencies (like WebOb) on the same minor versions. 

Changing every single text response in a site is definitely something what needs to be written in official Pyramid upgrade guides and shown on the console as depreciation warnings before committing change.

**Comment by bertjwregeer** [comment]
This is documented in the What's New in 1.7: http://docs.webob.org/en/stable/whatsnew-1.7.html

-----

Change `body` to `text` in your call to `Response` to use the new `default_body_encoding` to encode the text appropriately for the response.

`body` is supposed to be  a binary type`b'body here'`, and for non-text content-types this has been changed so that WebOb will now raise an exception.

Unfortunately the changes in WebOb 1.7 which fix a LOT of reported issues (here and on IRC) had as side effect that non-text content-types will no longer get encoded, nor will the default charset be added to the Content-Type's that are not text ones.

-----

Previously Response would have turned your content-type sent to the client to:

    application/vnd.geo+json; charset=UTF-8

Which is not a valid content-type for `application/*` since charset only applies to "text" content-types only.

-----

As for Pyramid, Pyramid depends on certain versions of WebOb because of features it provides. Pyramid 1.8 will depend on WebOb 1.7. Older versions of Pyramid require WebOb 1.3 (IIRC) and higher.

Pyramid does not explicitly pin a dependency to a particular version because there is no requirement, and we do testing to make sure that WebOb changes don't break supported versions of Pyramid (by running the test suite against various versions).

For deployments it is recommended that people "freeze" versions themselves, and mange pinning yourself. This is best practice in the software world, Python or otherwise.

**Comment by hyperknot** [comment]
Thanks for the detailed explanation! Actually, after reading through the whole upgrade notes, I didn't understand the change effecting me very well, but your answer explained it very clearly.

So the right way to provide a downloadable file is:
- If it is human readable (JSON, XML, etc), I should supply a unicode string (such as generated by json.dumps, ensure_ascii=True), to Response(text=...)?
- If it is binary file, such as an `image/jpeg`, I should supply a byte string to Response(body=...)?

Is that right?

About the Pyramid situation, I strongly disagree, and it'd be unheard of in Django for example if pinning a given Django version would introduce such silent changes, but it is out of the scope of this ticket.

**Comment by bertjwregeer** [comment]
If the Content-Type is text based: `text/*` or `application/*+xml`, then the `charset` applies (if none is supplied, `default_charset` is used) because you want the browser to know how to decode the responses. Using `text` would be best, but `body` continues to work because we know how to `encode()` the string provided.

For non-text based content-types, like `image/jpeg` we can't automatically `encode()`, and users should instead supply a byte string instead as you mentioned.

----

Regarding your last comment, Django is different, it includes everything all in one package, Pyramid is built up from different packages. Best practice still, even with Django, especially if you use third party packages as well, is to pin all dependencies all the way down.

**Comment by piotr-dobrogost** [comment]
Out of all mime types only `text/*` and `application/*+xml` are specified as text based?

**Comment by mmerickel** [comment]
@piotr-dobrogost By default, yes. You can specify `response.charset = 'utf8'` on anything to specify you really want a charset.

**Comment by piotr-dobrogost** [comment]
I understand this but was rather looking for a spec/reason for only these two specified as text based.

**Comment by mmerickel** [comment]
I don't think we can really be expected to track every text-based mime-type. Even the list of mimetypes varies between systems. Werkzeug makes this same decision.

**Comment by bertjwregeer** [comment]
`application/*+xml` is already an exception, since `application/*` is technically binary only (that is the way it is defined in the mime-type registry). This is why `application/json` doesn't have a charset, yet most people treat it like it does since it happens to be text. It should most likely have been `text/json` but alas, we are stuck with it now.

@hyperknot `vnd.geo+json` has been deprecated, and instead `application/geo+json` should be used: http://www.iana.org/assignments/media-types/application/geo+json, note:

> Encoding considerations:  binary

As well.

**Comment by hyperknot** [comment]
The same is said for `application/json` as well.
http://www.iana.org/assignments/media-types/application/json

It even says: Note:  No "charset" parameter is defined for this registration. Adding one really has no effect on compliant recipients.

**Comment by hyperknot** [comment]
I still don't get why should I tread JSON different from XML? Why is a standard saying that XML should be treated as text, while JSON as binary?

So the right way of handling JSON via web is to use ensure_ascii=True?

**Comment by mmerickel** [comment]
> I still don't get why should I tread JSON different from XML? Why is a standard saying that XML should be treated as text, while JSON as binary?

We didn't write the spec. What do you want us to do?

**Comment by hyperknot** [comment]
Sorry, I was just trying to understand it. So afaik, from my experiments:

1. The build in JSON response (for example JSON renderer in Pyramid) uses ensure_ascii=True to escape the non-ascii characters and the generated file is actually ascii. However this requires a JSON compliant client to actually understand and unescape them. If I use this to generate a downloaded file it'd contain the escape sequences.
2. In my case, where I actually want an unicode encoded file to be downloaded, I need to use `ensure_ascii=False` and either `text=s` or `body=s.encode('utf8')` if I understand right.
3. WebOb is trying to magically fix XML types by auto-encoding them to `utf8`, so it doesn't matter how they are supplied.

Is that right?

**Comment by mmerickel** [comment]
I really don't know what you're talking about with `ensure_ascii`. It's completely irrelevant to webob. `application/json` is a utf-encoded mime-type and fully supports unicode. As far as XML it does not define an encoding and thus webob defaults to utf8 unless you specify otherwise. You can even define your own charset for json, but then it's violating the mimetype spec.

**Comment by hyperknot** [comment]
I was talking about when using Pyramid's `@view_config(..., renderer='json')` predicate. This doesn't return an unicode encoded JSON, but an ascii string with escape sequences like: `\u0151`, what happens with encode_ascii=True (which is the default).

**Comment by bertjwregeer** [comment]
By default the Pyramid `json` renders uses `json.dumps`: https://github.com/Pylons/pyramid/blob/master/pyramid/renderers.py#L229

Which is used here to render the view: https://github.com/Pylons/pyramid/blob/master/pyramid/renderers.py#L275

Then in `RendererHelper` since the result is `string_type` it is assigned to `response.text`: https://github.com/Pylons/pyramid/blob/master/pyramid/renderers.py#L468

`Response.text` will use `default_body_encoding` to set the body: https://github.com/Pylons/webob/blob/master/webob/response.py#L648

There is no `ensure_ascii` anywhere.

You return a `dict()` from your view, that then gets rendered and gets turned into a WebOb `response` that has `__call__` called on it to turn it into a WSGI response, that WSGI response has a byte string body, which if you were to print it to the console would have the unicode ascii escape sequences, but that is not what the client receives.

**Comment by hyperknot** [comment]
`ensure_ascii` is True by default in json.dumps. That's why it's not in the source code.

The actual JSON presented to the client is containing the escape characters. I'm not talking about Python's output, but curl for example.

Probably not a big problem, but might produce smaller files if they would be encoded.

**Comment by bertjwregeer** [comment]
> Sorry, I was just trying to understand it. So afaik, from my experiments:

> - The build in JSON response (for example JSON renderer in Pyramid) uses ensure_ascii=True to escape the non-ascii characters and the generated file is actually ascii. However this requires a JSON compliant client to actually understand and unescape them. If I use this to generate a downloaded file it'd contain the escape sequences.

Nope, see above response.

> - In my case, where I actually want an unicode encoded file to be downloaded, I need to use ensure_ascii=False and either text=s or body=s.encode('utf8') if I understand right.

There is no ensure_ascii, in your case you can create a response as follows:

Explicitly encode to provide a byte string:

```
resp = Response(content_type='application/vnd.geo+json',
           content_disposition=u'attachment; filename="{}.geojson"'.format(basename),
           body=body.encode('utf-8'))
```

or, use the `.text` attr, which uses `default_body_encoding`:

```
resp = Response(content_type='application/vnd.geo+json',
           content_disposition=u'attachment; filename="{}.geojson"'.format(basename),
           text=body)
```

or, use `json_body` to have `json.dumps` automatically called for you:

```
resp = Response(content_type='application/vnd.geo+json',
           content_disposition=u'attachment; filename="{}.geojson"'.format(basename),
           json_body=map_obj.geojson)
```

or, since you are using pyramid, so long as you set the renderer on the view to JSON:

```
resp = request.response
resp.content_type = 'application/vnd.geo+json'
resp.content_disposition=u'attachment; filename="{}.geojson"'.format(basename)

return map_obj.geojson
```

> - WebOb is trying to magically fix XML types by auto-encoding them to utf8, so it doesn't matter how they are supplied.

No, WebOb will only auto-encode when you give `Response` a `body` parameter that is NOT a byte string. It's trying to be helpful. This was added some versions ago, unfortunately and it leads to issues like the ones above. The goal was to support stuff like this:

```
res = Response('some text')
```

This leads to issues when the `content_type` doesn't have a charset since how is WebOb supposed to know HOW to encode the string provided?

So ONLY for text type Content-Type's will WebOb allow you to pass a `string_type` to `body`, and it will attempt to automatically encode it. It is for those text-type Content-Type's that WebOb will also automatically add the `default_charset`. If your content-type is not text, no default charset is added to the Content-Type.

> Is that right?

No.

**Comment by bertjwregeer** [comment]
@hyperknot Then register a new renderer for `json` that has a lambda function that calls `json.dumps` with `ensure_ascii=False`. This is possible with the current implementation that is in Pyramid...

**Comment by hyperknot** [comment]
@bertjwregeer I was referring to the auto-encoding as magic, without any negative meaning.

About points 1. and 2., have a `curl` look at a non-ascii JSON response, it will actually contain the escape sequences. I've updated my answer above with a Flask config reference for `JSON_AS_ASCII`.

**Comment by bertjwregeer** [comment]
For Pyramid:

```
import json
from pyramid.renderers import JSON

config.add_renderer('json', JSON(indent=4, ensure_ascii=False))
```

Now `ensure_ascii` will be set to `False` when calling `json.dumps`.

**Comment by bertjwregeer** [comment]
> About points 1. and 2., have a curl look at a non-ascii JSON response, it will actually contain the escape sequences.

Yes, you are correct, I didn't realise the standard library made such a stupid choice. You will have to use either `body=body.encode('utf-8')` or `text=body`.

**Comment by hyperknot** [comment]
Thanks for all the details, hopefully this thread will help future users as it contains a lot of useful information now (and GitHub threads always end up at top google search results).

**Comment by eode** [comment]
I know this is old and closed, but I just wanted to throw this in there:

JSON is defined as the mimetype `application/json` because it is actually binary.  It is a part of the [JSON Spec1](https://tools.ietf.org/html/rfc7158#section-8.1) that JSON MUST encoded as UTF-8 (default, smaller, and most interoperable), UTF-16, or UTF-32, without BOM, and that the default is UTF-8 (basically because nobody likes UTF-16 or UTF-32, because UTF-8 is better).

I don't really know why python's json lib doesn't return UTF-8, but it's definitely something that's easily remedied.  On the web server/client side, the assumption should probably be that it's UTF-8.
