### ISSUE TITLE
WebOb 1.7.0 breaks backwards compatibility of Request.is_body_readable

### ISSUE THREAD

**Issue by sigmavirus24** [Pylons/webob#307]
The refactor in [this commit](https://github.com/Pylons/webob/commit/0e6fcbfbc58af6fdd4e125543bf8f5fb91b984c6) has broken existing code in openstack/glance.

Previously, Glance would decide if it could process a body based on the transfer encoding and this attribute, specifically it uses [this method](https://github.com/openstack/glance/blob/b7c627ef68c303d4c3182c1a41b36185447039a3/glance/common/wsgi.py#L993..L1006). We call that [here](https://github.com/openstack/glance/blob/b7c627ef68c303d4c3182c1a41b36185447039a3/glance/api/v1/images.py#L1238) and if that `is_body_readable` returns False, then we act as if there is no body data.

The test in particular that led me to this doesn't specify a body, but it never has. I would agree with you that this is more accurate since it seems we were relying on `http_method_probably_has_body`.

We can implement that behaviour, but a note about this would have been helpful in the release notes.

**Comment by bertjwregeer** [comment]
I can add a note to the release notes. WSGI spec officially doesn't support transfer-encoding for incoming requests, which is why the change was made.

----

I would recommend adding a body to the test. Just because the request might have a body does not mean it does, this led to various issues whereby for example if you sent a POST without body it could hang the WSGI server (wsgiref is particularly vulnerable to this).

If you are absolutely sure that the request has a body, but there is no content-length, set `webob.is_body_readable` in the environ, this would allow WebOb to ignore the fact that there is no Content-Length and still read the body as necessary.

**Comment by sigmavirus24** [comment]
@bertjwregeer so that was just one example, as I found in other places, Glance actively tries to support a chunked TE. So we had to [add checks](https://review.openstack.org/423366/) for that encoding and force `is_body_readable` to True. Luckily, that fix will work for both WebOb 1.7 and WebOb pre-1.7.

Thanks for the head's up. I'm going to create a bug for that on Monday

**Comment by bertjwregeer** [comment]
Was about to release a new version of 1.7, and figured I'd update the changelog, but there is already a comment there in the backwards incompatibility:

> WebOb no longer supports Chunked Encoding, this means that if you are using WebOb and need Chunked Encoding you will be required to have a proxy that unchunks the request for you. Please read https://github.com/Pylons/webob/issues/279 for more background.

I'll specifically mention that `is_body_readable` no longer assumes a body is readable by just being a particular HTTP verb.
