### ISSUE TITLE
API documentation only includes docstrings for `Accept` and `MIMEAccept`

### ISSUE THREAD

**Issue by whiteroses** [Pylons/webob#323]
See also https://github.com/Pylons/webob/pull/327#issuecomment-309230004 [edited @stevepiercy]

Currently the Accept\* headers related API documentation is set up as follows:

    Accept-*
    ~~~~~~~~

    .. automodule:: webob.acceptparse
    .. autoclass:: Accept
       :members:
    .. autoclass:: MIMEAccept
       :members:

This means that currently only the `Accept` and `MIMEAccept` classes are included, and only their non-inherited member functions and properties with docstrings are currently documented. I think we'd want all the classes in acceptparse.py to be documented, and inherited methods that are part of the API documented for each inheriting class? It also would be better I think not to rely on the presence of docstrings to decide which member functions and properties are documented; for example, right now in the docs:

<blockquote>
class webob.acceptparse.MIMEAccept(header_value)
Represents the Accept header, which is a list of mimetypes.

This class knows about mime wildcards, like image/*

accept_html()
Returns true if any HTML-like type is accepted

accepts_html
Returns true if any HTML-like type is accepted
</blockquote>

I don't think it was intended for `accept_html()` to be documented (since we have `accepts_html`, `accept_html()` probably isn't intended to be part of the API?)

Sphinx has directives for these changes, and if you agree this needs to be changed, I can fix this.

**Comment by bertjwregeer** [comment]
Documentation is a point where WebOb certainly needs a lot of improvement. I'd be very happy to accept changes to documentation to improve thing for consumers of the library.

**Comment by mmerickel** [comment]
You can look at pyramids request docs for some examples of sphinx directives here. For example there are `:inherited-members:` and some sort of ignore or exclude directives to better control the docs.

**Comment by whiteroses** [comment]
Thanks, I'll check Pyramid's request docs too. I'd found the directives like `:inherited-members` in the Sphinx docs, but will need a little time to get familiar with Sphinx, and to come up with the right docstrings for the classes/member functions/properties that don't have any. Happy to fix.

There are other things I'd like to help improve for the docs, but better focus on the Accept\*-related parts for now :)

**Comment by whiteroses** [comment]
I worked on resolving this issue, and bumped into some bugs in Sphinx, to do with `:members` and `:inherited-members`; but they could be replaced with ``automethod`` and ``autoattribute``, so not a big problem. But now there are a couple of questions that need to be decided, before I can submit the PR and close this issue:

1. Right now only `Accept` and `MIMEAccept` are documented; I don't know if the other classes like `AcceptCharset` and `AcceptLanguage` not being documented was an oversight, or if they were meant to be represented by the `Accept` class, and the user was supposed to realise that these classes inherited from `Accept` (I don't see where the user would get this information without guessing or looking at the source). So we would like each class to be documented; and I did the work for that, before it occurred to me: arguably, `best_match` and `quality` have only been documented as public API for `Accept`, which was a public-facing class only for `request.accept_encoding` (which used to return an instance of `Accept`). It looks like `best_match` and `quality` may need to change at some point or may not make sense any more, and if I were to document them now, that would in fact be locking them in! Or maybe I'm just reaching? (And that they were public API for the other classes anyway, even though documenting them via the `Accept` class was far from clear.) What do you think?

2. Currently you can see that `MIMEAccept` has `accept_html()` and `accepts_html` documented, and they appear to be the same thing: looking at the source suggests we can combine the two into an `accepts_html` property (with `@property`). But they are currently both documented. Change/leave as is?

**Comment by bertjwregeer** [comment]
1. Any documentation added now that needs to be removed in the future, so long as it is not published (i.e. no new release cut) can safely be removed later. There is no issue with documenting things as they are now (and potentially even backport em to older branches where it still holds true).
2. Leave it as is for now, we can worry about changing them later. `accepts_html` is already a property, the other is if you want a function to call. I don't know how widely used they are, and with a deprecation period maybe we could remove them/modify them but I am not too worried about it for right now.

**Comment by whiteroses** [comment]
Ok, if you're not planning any new releases until all this is done, I'll submit the PR to improve the docs for now. With 2., I can see why we'd want the function *or* the property, but can't see why anyone would want both; and they have such similiar names that it seems to be an invitation for bugs and typos. But will leave as is for now :)

**Comment by bertjwregeer** [comment]
I have no plans to release a new version of WebOb in the near future.

**Comment by whiteroses** [comment]
Hopefully you'll want to release a new version after GSoC is done? :)

**Comment by stevepiercy** [comment]
I looked into this. Check your version of Sphinx in your virtual environment. I have Sphinx 1.5.6 (the latest 1.5.x line, since RTD does not yet support 1.6.x and because 1.6.x also nags about not using "html_smarty_pants").

I also wonder whether you did something different when installing webob so that it could be autodoc'ed? I did a `pip install -e ".[docs]"` so that I would install webob and its doc dependencies in editable mode.

Using Sphinx 1.5.6 (I had to specify the version), I was unable to reproduce the issue. That might be because I could not follow the instructions @whiteroses provided in the [original report](https://github.com/Pylons/webob/pull/327#issuecomment-309230004). One, single, reproducible example is sufficient. Keep it short and sweet, otherwise I have a hard time following your monologue. Copy-pasta is not better than a branch with an example that I can just check out.

Here's what I did:

- checkout new branch off of master, arbitrarily named [docs-fix-autodoc](https://github.com/stevepiercy/webob/tree/docs-fix-autodoc)
- open `docs/api/webob.txt`
- replace this:
   ```
   .. autoclass:: MIMEAccept

   .. autoattribute:: accepts_html
   .. automethod:: accept_html
   .. automethod:: best_match
   .. automethod:: parse
   .. automethod:: quality
   ```
   with this:
   ```
   .. autoclass:: MIMEAccept
       :members:
       :inherited-members:
   ```

In both examples, the rendered HTML from Sphinx is identical with one exception. In the former `accepts_html` appears before `accept_html()`. In the latter, those two swap their order. See attached screenshots for comparison.

## automethod/autoattribute
![automethod](https://user-images.githubusercontent.com/102112/27379302-9303ca44-562f-11e7-9fe1-83bb1a15aeb4.png)

## members/inherited-members
![members](https://user-images.githubusercontent.com/102112/27379301-92f14dce-562f-11e7-8d8a-9b35fdf63a5b.png)

**Comment by bertjwregeer** [comment]
You are using tox, no?

`tox -e docs` 

will build the docs. If we need to pin Sphinx because of issues with a newer version then let's do that!

**Comment by stevepiercy** [comment]
I was not. So I tried `tox -e docs`, and I got the exact same result as "members/inherited-members" above. I'm not sure how to reproduce the reported issue.

I wouldn't pin Sphinx at this time. If you happen to install Sphinx ≥1.6 locally, then just be aware that you'll get nagged by [this issue and can resolve it](https://github.com/rtfd/readthedocs.org/issues/2940). RTD currently uses 1.5.x, and pinning to less than Sphinx 1.6 might cause us to miss their potential future upgrade.

**Comment by whiteroses** [comment]
Sorry @stevepiercy, much of it is my mistake: I missed the word *all* in "For classes and exceptions, members inherited from base classes will be left out when documenting all members, unless you give the `inherited-members` flag option, in addition to `members`". So I was trying to use `:inherited-members:` with `:members:` and an explicit list of members, which created all sorts of problems. And I was trying to use an explicit list of members partly because members were not showing up as expected, as I was using `:inherited-members` incorrectly; and partly because I wasn't sure `MIMEAccept.accept_html` should be part of the documented public API, and it made me think that it would be a good idea to use an explicit list in general to have that control (bertjwregeer has since said we can leave `accept_html` documented for now). Long story short, `:members:` and `:inherited-members:` will do fine for now.

There is one issue (assuming I haven't made another mistake, and it isn't a figment of my imagination): the *static* label is missing for `.parse()` under `AcceptEncoding` and `AcceptLanguage`, the two classes that inherit `.parse()` without overriding. Here's a branch that should demonstrate the issue: https://github.com/whiteroses/webob/tree/fix-acceptparse-docs.

I will submit a PR with the branch for now, because the label thing is minor. Sorry again for the mistake and time wasted &mdash; if the problems were what I thought they were, those steps would have been necessary to reproduce the various issues, though I should still have started you off with a branch for step 1. Hope the branch demonstrates the issue this time.

And I was using Sphinx 1.6.2, but was using the virtualenv created by tox in .tox/docs with `sphinx-build` because the computer I'm working on right now is old and slow, and `tox -e docs` includes epub as well, so testing every little change with it was far, far too slow. That in itself might have (and did) create issues, thought I did always check with `tox -e docs` at the end.

**Comment by stevepiercy** [comment]
@whiteroses no need to apologize, and I'm glad it was a mere misinterpretation. Sometimes it hits me when I start to write up an [MCVE](https://stackoverflow.com/help/mcve) in an issue tracker, or do [rubber ducking](https://en.wikipedia.org/wiki/Rubber_duck_debugging).

I see the issue with the `static` decorator not getting applied to the two subclasses. I think there is an [open issue for Sphinx](https://github.com/sphinx-doc/sphinx/issues/478), if I understand correctly. I tried the suggested "fix" in that issue by editing `env/lib/python3.6/site-packages/sphinx/ext/autodoc.py`, but there was no change. There are [several other issues with "decorator" in their description](https://github.com/sphinx-doc/sphinx/issues?utf8=%E2%9C%93&q=decorator).

To speed up tox, edit your `tox.ini`, removing the `epub` builder, just remember not to commit it:

```ini
[testenv:docs]
basepython = python3.6
whitelist_externals = make
commands =
    pip install webob[docs]
    make -C docs html BUILDDIR={envdir} "SPHINXOPTS=-W -E"
```

**Comment by whiteroses** [comment]
MCVE next time!

I looked at the first open issue for Sphinx that you linked to (briefly), and it says "It would obviously not work for auto//discovered// functions/methods, or those listed in {{{:members:}}}", so it may not be what we're looking for? We do get the `static` label in the classes where the static method is overridden, so we shouldn't need to add any extra directives or options. But it is a relatively minor thing &mdash; we can keep this issue open, and maybe come back to it at a later point?

Editing `tox.ini`: of course! Somehow that didn't occur to me. But I was also using `sphinx-build` because it allowed me to specify a specific file &mdash; I don't know Sphinx well enough, and didn't have enough time to dig into, whether it was actually saving me much time, but it would sometimes not update the file for reasons I could not (and did not have time to) fathom, which was driving me mad. So I've gone back to using tox for now, and your tip will be helpful, thanks. At least there's always other work to do while I wait...

**Comment by stevepiercy** [comment]
I think this issue as originally reported can be closed.

There's a new issue about decorators that you could report under webob or not. It's both very minor and something that is within Sphinx. Moreover, the end result of this GSoC project has a good chance to obviate the issue. I'd say "not report".

Sphinx caches objects in doctrees. It definitely caches Sphinx source files (reStructuredText files),  and it only rewrites new or changed reST files. I do not know whether it also caches a package's docstrings or even looks at changes therein.

Here's my unproven theory. You edited the WebOb docstrings, but did not edit the reST file. Since Sphinx saw no changes to or new reST files, it wrote no updates, and you observed none. You can force Sphinx to rebuild the HTML in a number of ways, including:

- deleting its corresponding doctree file
- editing and saving the reST file which refers to the package's docstrings through autodoc stuff
- use the [`-a`](http://www.sphinx-doc.org/en/stable/invocation.html#cmdoption-sphinx-build-a) flag for `sphinx-build`

Since there are few doc files in webob, I would use the last option. With lots of doc files, like in Pyramid, I would do the second option, temporarily inserting a carriage return or something innocuous.

**Comment by whiteroses** [comment]
Oh yeah of course, we hopefully won't need to document an inherited static method. Ok, I'll close this issue.

Yes, I didn't have time to figure out how and where Sphinx does its caching. Almost all my changes were in the reST file though, so that wasn't the reason I don't think. I tried the -a flag too, but we can't use the flag when specifying a file. But you're right, there aren't many doc files, so specifying a file probably doesn't make much difference in speed. I'll see if I can get it to work a bit more smoothly next time we need to document something. Thanks!
