### ISSUE TITLE
Regression in Accept header best_match if media type is provided

### ISSUE THREAD

**Issue by jd** [Pylons/webob#355]
The following test fails in webob 1.8.0:

```diff
diff --git a/tests/test_acceptparse.py b/tests/test_acceptparse.py
index 01eb4d0..dc74532 100644
--- a/tests/test_acceptparse.py
+++ b/tests/test_acceptparse.py
@@ -1069,6 +1069,10 @@ class TestAcceptValidHeader(object):
         )
         assert accept.best_match(['text/html', 'baz/gort']) == 'baz/gort'

+    def test_best_match_json_details(self):
+        accept = AcceptValidHeader('application/json; details=true')
+        assert accept.best_match(['application/json']) == 'application/json'
+
     def test_best_match_json(self):
         accept = AcceptValidHeader('text/html, */*; q=0.2')
         assert accept.best_match(['application/json']) == 'application/json'
```

This affects Pecan and therefore https://github.com/gnocchixyz/gnocchi/issues/852

**Comment by bertjwregeer** [comment]
According to the standard `application/json; detail=true` is not equal to or the same as `application/json`. This only happens to have worked in the past due to the old `MIMEAccept` code stripping off the media parameters.

Since `best_match` is deprecated and going away, `acceptable_offers` should be used instead, however that also returns an empty list signifigyin that `application/json` is not acceptable for `application/json;detail=true` which is technically true, but not very helpful.

I'd like to understand the use case for using media parameters better, and understand how it is used in the code and what the failure scenarios is, before I go adding updated API's to deal with it... I've been trying to look through gnocchi, and trying to find the failures but all I find is where you pin WebOb, and I have no stack trace and no reference point to even understand how or where you are using `history=true` or `details=true` to be able to provide guidance.

Since `best_match` is going away, even if I were to add a hack for it to ignore the media parameters, it would be temporary!

**Comment by bertjwregeer** [comment]
So, looking at this some more, it looks like the user agent is sending the wrong `Accept` header. If you want to specify accept parameters, you need to provide a `q=` weight parameter:

>   Each media-range might be followed by zero or more applicable media
>   type parameters (e.g., charset), an optional "q" parameter for
>   indicating a relative weight (Section 5.3.1), and then zero or more
>   extension parameters.  The "q" parameter is necessary if any
>   extensions (accept-ext) are present, since it acts as a separator
>   between the two parameter sets.```

- https://tools.ietf.org/html/rfc7231#section-5.3.2

For example:

```
>>> accept = create_accept_header('application/json; details=true')
>>> accept
<AcceptValidHeader ('application/json;details=true')>
>>> accept.parsed
[('application/json;details=true', 1.0, [('details', 'true')], [])]
>>> accept2 = create_accept_header('application/json; q=1.0; details=true')
>>> accept2
<AcceptValidHeader ('application/json;q=1;details=true')>
>>> accept2.parsed
[('application/json', 1.0, [], [('details', 'true')])]
>>> accept2.acceptable_offers(['application/json'])
[('application/json', 1.0)]
>>> 'application/json' in accept
False
>>> 'application/json' in accept2
True
```

Another example, showing multiple types that are acceptable to the user agent with different accept parameters:

```
>>> accept3 = create_accept_header('application/json;q=1.0;details=true, text/html;q=0.9;details=false')
>>> accept3
<AcceptValidHeader ('application/json;q=1;details=true, text/html;q=0.9;details=false')>
>>> accept3.parsed
[('application/json', 1.0, [], [('details', 'true')]), ('text/html', 0.9, [], [('details', 'false')])]
>>> accept3.acceptable_offers(['text/html', 'application/json'])
[('application/json', 1.0), ('text/html', 0.9)]
```

The client's `Accept` is sending media params when they likely meant to send accept parameters.

According to the standard, which we now implement more strictly, `application/json;details=true` is not equal to `application/json` and are considered two different types, and returning `application/json` for a request asking for `application/json;details=true` is not correct.
At this point in time I may add a shim to `MIMEAccept`'s `best_match`

Do note that `application/json` as a registration does not have any applicable required parameters or optional parameters and is a binary type (that happens to be UTF-8 encoded).

**Comment by jd** [comment]
@bertjwregeer This is used as a parameter for the returned content, e.g. it includes more info. It might be bad idea and is already exposed as a query parameter anyway.

In the end your analysis seems right, we probably should not have used that in the first place, and the fact that it worked before just did not warn us that we were doing something foolish.

I'll go ahead and remove that code on our side, and I think we should be able to close this bug.

**Comment by bertjwregeer** [comment]
Thank you for following up. If you have any other issues please let me know :-).

**Comment by jd** [comment]
@bertjwregeer Thank **you** for taking time to dig into our issue and provide clear explanations. You rock!
