### ISSUE TITLE
No changelog/history entry for 1.8.1 release

### ISSUE THREAD

**Issue by reedstrm** [Pylons/webob#357]
Looks like y'all have changed your policy on changelogs, moving them to HISTORY.txt, but keeping current unreleased changes in CHANGES.txt That's fine except the release process missed the memo: you just release 1.8.1 without moving the entry (apparently a regression fix ) from CHANGES to HISTORY, so wehen  pyup-bot sent me a nice PR for updating, it couldn't tell me about the changes. Hmm, on digging further, I see a docs/changes.txt that includes both of those files. And I see the website docs updated https://docs.pylonsproject.org/projects/webob/en/stable/changes.html - is that a dynamically generated page now? Is there no hope for pyup to find the current release text? Help me, WebOb devs, you're our only hope! 

I've cross-filed an issue over at changelogs, i case there needs to be some new code for parsing this. Unless it was just an oversight during release. https://github.com/pyupio/changelogs/issues/110

**Comment by mmerickel** [comment]
@reedstrm it's standard practice for us to keep CHANGES.txt focused on the upcoming major release and we archive the history of previous major releases in HISTORY.txt. If you want to track the changes for the 1.8 series specifically then look at CHANGES.txt on the 1.8-branch [1]. Bugfix releases will always be on release branches, not on master. Similarly the website by default is pointing at the latest stable branch which is 1.8-branch which is why you see the changelog for 1.8.1 on there.

If I had to make a suggestion I'd say the most reliable way to get changes is from the changelog/readme in the sdist uploaded to pypi.

This is how Pyramid works, as well, and has for a very long time.

[1] https://github.com/Pylons/webob/blob/1.8-branch/CHANGES.txt

**Comment by bertjwregeer** [comment]
You just made me realise that the `wsgi.input_terminated` change that went into 1.7.4 was not documented correctly on master which then became 1.8.0. Anyway...

@mmerickel is correct, for point releases on major versions (1.6.x, 1.7.x, 1.8.x) the CHANGES.txt is only updated for the branch that it is created from. master is going to become the new `1.9.x` eventually, and the same thing will happen.

`HISTORY.txt` doesn't accurately portray the point releases either. At this point I am not sure how to reconcile that to be honest, since the history diverges as soon as we create a new 1.y-branch and it is no longer linear, and I really don't want to copy and paste from the 1.y-branches.

@mmerickel's suggestion of pyup using the information that is uploaded to PyPi is the best course forward.
