### ISSUE TITLE
Feature suggestion: body encoding by chunk.

### ISSUE THREAD

**Issue by Xeite** [Pylons/webob#360]
Hi.

When I was using OpenStack glance API, there was abnormally high memory usage, and I tried to dig the why.

I found glance api uses webob response for image download, and by further investigation large image file was loaded in memory at once in here (https://github.com/Pylons/webob/blob/master/src/webob/response.py#L534)

imho, if there were API which could specify the unit of payload, it works well for large file transfer without memory consumption.

Thanks!

**Comment by bertjwregeer** [comment]
I am not sure whether you are talking about sending a `Response` back to a client or if `glance` is using WebOb to make requests to a remote server and is using the `Response` object to read the entire file.

That being said, if you are responding with a file, you can use:

```
response.body_file = 'pathtofilehere'
```

Which correctly sets up chunking while reading the file.

Accessing `response.body` at this point is unwise since the only way for WebOb to provide the body at that point is to read the entire thing into a byte string.

If you need to know if there body exists, there is a `response.has_body` that will be `True` if the response has a body and `False` if it does not.

https://github.com/Pylons/webob/blob/master/src/webob/response.py#L671

**Comment by mmerickel** [comment]
Side note, it probably wouldn't be a bad idea to add https://github.com/Pylons/pyramid/blob/85900228894814105aa882e1e71f1e4e69090a9e/pyramid/response.py#L32-L77 to webob which supports `wsgi.file_wrapper` which can use sendfile on conforming wsgi servers to avoid even reading the data in the worker threads.
