### ISSUE TITLE
validate media types consistently in acceptable_offers

### ISSUE THREAD

**Issue by mmerickel** [Pylons/webob#365]
```python
>>> create_accept_header('').acceptable_offers(['foo'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michael/work/oss/pyramid/env/lib/python3.6/site-packages/webob/acceptparse.py", line 804, in acceptable_offers
    raise ValueError(repr(offer) + ' is not a media type.')
ValueError: 'foo' is not a media type.
>>> create_accept_header('*/*').acceptable_offers(['foo'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michael/work/oss/pyramid/env/lib/python3.6/site-packages/webob/acceptparse.py", line 804, in acceptable_offers
    raise ValueError(repr(offer) + ' is not a media type.')
ValueError: 'foo' is not a media type.
>>> create_accept_header('invalid/x/y').acceptable_offers(['foo'])
[('foo', 1.0)]
>>> create_accept_header(None).acceptable_offers(['foo'])
[('foo', 1.0)]
```

It's not ok to raise here in some scenarios and not in others. The offer is server-side and webob should handle it consistently by validating those parameters the same always.

I went backward and found out that webob < 1.5 actually did this consistently but after that it stopped calling `_check_offer` in `MIMEAccept` but kept calling it in `MIMENilAccept`.

**Comment by whiteroses** [comment]
I had noticed this when I was looking at the issue in Pyramid, and was going to create an issue to ask for your opinions when I had some time.

From [RFC 7231, 3.1.1.1.  Media Type](https://tools.ietf.org/html/rfc7231#section-3.1.1.1), the definition of the syntax for a media type is:

    media-type = type "/" subtype *( OWS ";" OWS parameter )
    type       = token
    subtype    = token

and from [RFC 7231, 5.3.2.  Accept](https://tools.ietf.org/html/rfc7231#section-5.3.2), the definition of the syntax for a media range is:

    media-range    = ( "*/*"
                     / ( type "/" "*" )
                     / ( type "/" subtype )
                     ) *( OWS ";" OWS parameter )

These work out to be exactly the same, because a `type` is a `token`, and a `token` [may contain `*`s](https://tools.ietf.org/html/rfc7230#section-3.2.6). So a media type is a media range and vice versa by definition of their syntaxes; `*/*`, `text/*`, `*/text`, `*text*/***` are all valid media types *and* media ranges.

But [the section on the Accept header](https://tools.ietf.org/html/rfc7231#section-5.3.2) then goes on to say:

    The asterisk "*" character is used to group media types into ranges,
    with "*/*" indicating all media types and "type/*" indicating all
    subtypes of that type.  The media-range can include media type
    parameters that are applicable to that range.

which is why we refer to e.g. `*/*` and `text/*` as media ranges, and e.g. 'text/html' as media types. I'll distinguish them by referring to the former as the ABNF definition of media type and media range, and the latter as the human definition.

`acceptable_offers` needs to parse the offers in its `offers` argument, so it uses a regex based on the ABNF definition of a media type/range to do so. In parsing, the regex necessarily validates the offer according to the ABNF definition, but it wasn't intended as validation (as I noted in the comment [here](https://github.com/Pylons/webob/blob/master/src/webob/acceptparse.py#L801), in one of those comments that must've seemed clear at the time but cryptic now &mdash; I will submit PR to clarify or remove depending on outcome of this discussion) &mdash; it is a value provided by the developer, and we don't generally validate such arguments. More importantly, it does not prevent an offer that is a media range by the human definition:

    >>> create_accept_header('*/*').acceptable_offers(['*/*'])
    [('*/*', 1.0)]
    >>> create_accept_header('*/*').acceptable_offers(['text/*'])
    [('text/*', 1.0)]

Or offers that we would not think made sense, such as:

    >>> create_accept_header('*/*').acceptable_offers(['*/html'])
    [('*/html', 1.0)]
    >>> create_accept_header('*/*').acceptable_offers(['***/***'])
    [('***/***', 1.0)]

as it is validating by the ABNF definition, but not by the human definition.

This validation does not do the same thing as [`_check_offer`](https://github.com/Pylons/webob/blob/1.7-branch/webob/acceptparse.py#L338), which simply checked for a '`*`' in the offer. But according to the ABNF definition of a media type from the RFC, a `*` may be found in a media type. So by the ABNF definition, we cannot `_check_offer` in `acceptable_offers`.

Imo validation of offers is not necessary, so my thinking at the time was to raise ValueError where we had to because of the parsing, and save the time and effort where the parsing wasn't necessary (for when the header was not present or was invalid). But I understand why we'd want to be consistent across all three classes, and can submit PR to validate in `AcceptNoHeader`'s and `AcceptInvalidHeader`'s `acceptable_offers` using the same regex. That would not prevent media ranges by the human definition or e.g `*/html` and `***/***` though &mdash; I guess we would have to document that this is only validating by the ABNF definition. Would that be ok?

**Comment by bertjwregeer** [comment]
If it is documented that it is validating by the ABNF definition then that is fine, so long as `AcceptNoHeader`, `AcceptInvalidHeader` and `AcceptValidHeader` all use the same validation, so that we are at least consistent.

**Comment by mmerickel** [comment]
How about if the api always doesn't raising and instead just fails to match them - never returning them in the result?

Side note on a use case: Pyramid's implementation will still exclude those confusing types at config-time to avoid any confusion because while the ABNF may allow it, I think we can all agree that no one should actually be putting a '*' in their media type and with Pyramid's compatibility history on the `accept` arg, it'd just be confusing to keep allowing it there.

**Comment by whiteroses** [comment]
I think it may be better not to raise at all, as long as we document that offers which are not valid media types by the ABNF definition are ignored/skipped &mdash; that ok?

**Comment by mmerickel** [comment]
I'm +1 on that behavior. Like I said for the accept predicate purposes I will still raise some errors within Pyramid but that is at config-time, not when Pyramid is handling requests and passing them to `acceptable_offers`.

**Comment by mmerickel** [comment]
I added an implementation of this in #372 that is ready for review.
