### ISSUE TITLE
Empty request.params for POST requests from fetch or axios

### ISSUE THREAD

**Issue by invisibleroads** [Pylons/webob#396]
Newer front-end clients recommend using `fetch` or `axios` for server requests. Both of these methods send POST data in the body of the request.

I spent a few hours trying to understand why POST requests sent via `fetch` or `axios` were generating empty `request.params` in [pyramid](https://github.com/Pylons/pyramid).

I later found the POST data in `request.body`.

```
In [1]: request.params
Out[1]: NestedMultiDict([])

In [2]: request.body
Out[2]: b'{"typeId":"p","name":"abc"}'

In [3]: request.json_body
Out[3]: {'typeId': 'p', 'name': 'abc'}
```

In case future developers run into the same issue, the solution is to look at `request.body` or `request.json_body`.

- Option 1: Update webob to populate `request.params` and `request.POST` from `request.json_body` for POST requests.
- Option 2: Update pyramid documentation to advise people to use `request.json_body` instead of `request.params` if using `fetch` or `axios`.

**Comment by bertjwregeer** [comment]
If you use `fetch` with a form encoded body (which `fetch` fully supports), it will correctly show up in `request.params`. `request.params` works for things you stuff into the URL (`request.GET` and anything that is `POST`ed that is form encoded, a.k.a `request.POST`) If you are sending a JSON body, it will be available in `request.json_body` and `request.body`.

Using `requests.params` could be a security issue since it mixes both `GET` and `POST` params together into a single dictionary, and you can't be sure if it comes from the `QUERY_STRING` or from the `POST`ed body.

Please do not tag various people into a ticket unnecessarily. Those that are following the repo will get the appropriate email, those that don't won't get an unnecessary email.

**Comment by invisibleroads** [comment]
Okay, sorry about tagging the other people. I wanted to tell them in case they run into the same issue.

1. I will submit a pull request to mention fetch and axios in https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/webob.html?highlight=post#dealing-with-a-json-encoded-request-body
2. I will add a message to the stack overflow question https://stackoverflow.com/questions/29775797/fetch-post-json-data to mention the pyramid solution
3. I will close this issue after remembering to do the above two tasks

**Comment by bertjwregeer** [comment]
I don't see Pyramid mentioned in the Stack Overflow question you linked to.

**Comment by stevepiercy** [comment]
> 1. I will submit a pull request to mention fetch and axios in https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/webob.html?highlight=post#dealing-with-a-json-encoded-request-body

I think this is unnecessary. If a developer chooses to use a specific library, then they should know what it does and how it works. Also we cannot control how a third-party library might change its interaction with Pyramid/WebOb, even if it is unlikely to do so.

**Comment by bertjwregeer** [comment]
@stevepiercy `fetch` is the new standard for doing XHR requests, replacing things like the jQuery `$.ajax` calls.

This will help people searching for the words "fetch", "pyramid", "json". So I think that change would actually be a good change.

I don't think it is worth mentioning axios.

**Comment by stevepiercy** [comment]
It would be fine in the [Pyramid Community Cookbook](https://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/).

**Comment by bertjwregeer** [comment]
A full example maybe, but in that link:

> This attribute is useful when you invoke a Pyramid view callable via, for example, jQuery's $.ajax function, which has the potential to send a request with a JSON-encoded body.

being updated to mention `fetch` as well, not just `jQuery` would be fantastic, since `fetch` is a browser standard and will be included everywhere like `XMLHTTPRequest`, but unlike `$.ajax` which only works if you use `jQuery`.

https://caniuse.com/#feat=fetch
