### ISSUE TITLE
Accepting "None" (string) value of cookie attribute SameSite.

### ISSUE THREAD

**Issue by marc1n** [Pylons/webob#406]
According to the new Cookie spec https://tools.ietf.org/html/draft-west-cookie-incrementalism-00
 all browsers should accept now "None" (string) value of SameSite attribute in Set-Cookie header.

This issue is a high priority because Chrome has already changed the default value of SameSite (see  https://blog.chromium.org/2019/10/developers-get-ready-for-new.html and https://www.chromium.org/updates/same-site).

**Comment by jvanasco** [comment]
I was just about to file this same bug.

My understanding of the spec and usage is that the string should be `None` (initial cap), not `none` (all lowercase).  Additionally, Chrome is forcing this change and Google websites are using "None" (leading capital N) in their own cookies.

**Comment by marc1n** [comment]
According to spec value of SameSite attribute is case insensitive.

**Comment by bertjwregeer** [comment]
I've merged the change into master. Sometime in the near future I'll do another release.

**Comment by wiewiorek** [comment]
Hi, are there any plans to do release soon? This feature is needed!

**Comment by bertjwregeer** [comment]
There were plans, however Google has a neat page that describes what will happen to older browsers that don't support the new spec:

https://www.chromium.org/updates/same-site/incompatible-clients

And this is not just a matter of users not upgrading, this is current software that is running on current devices that will not work.

This is why SameSite support is marked as experimental (it still is not a valid RFC), and why I am really frustrated with Google forcing a change through at such high speed.

Whose going to be responsible for when a new version of WebOb breaks existing sites because their authors are using Google's suggest value of setting cookies with SameSite to None?

**Comment by wiewiorek** [comment]
Hey! Thank you for your reply. I am sharing your concerns.

But I don't see how making possible to use SameSite="None" (string) within WebOb would cause anyone any trouble, if default would still be not to pass SameSite flag at all. Doing so would give a choice to developers to decide weather they would like to use it or not. Without that we are gonna need some dirty hacks to set this. 

What do you think about that?

**Comment by jvanasco** [comment]
Google already has this rolled out out to 50% of beta users, and is still targeting 100% of normal users next month.  It looks like 20% of my traffic is requiring a patched version of webob now; and that's jumping to 60% next month.  The incompatible browsers are an fraction of this traffic to me.

> Whose going to be responsible for when a new version of WebOb breaks existing sites because their authors are using Google's suggest value of setting cookies with SameSite to None?

I understand your concern about handling browsers that can't handle `"None"`, but this PR isn't setting it as the default value, it's just allowing that value to be set.  Deciding what cookie values to send, or use as defaults, should really be the concern for business logic in the application.

If you're really worried about safeguarding users, we could catch `"None"` to alert developers of  the browser implementation issues with `warnings.warn()`.  This stuff is likely to change though, which is why I don't think there should be any checking/validation of values.  a future version could accept a kwarg that is a function to handle 'is it okay to set this value'; there are lots of ways to handle that.

I dislike what google is doing here too. Heck, you will likely never meet anyone who dislikes google  more than I do.  But not having the ability to set this cookie value with webob is a big problem.

My point here is that it is a developer's choice to set `"None"` or `None`; they should have the ability to select what they want to send, and be responsible/empowered to fix it.

**Comment by mmerickel** [comment]
As long as webob isn't changing any default behavior it should be fine for it to ship the feature to support servers that want to use it. It's a popular enough feature that webob should have some support for it.
