### ISSUE TITLE
Awkward handling of Content-MD5 header with chunk transfer encoding

### ISSUE THREAD

**Issue by javacruft** [Pylons/webob#86]
I came across this when debugging test failures of Openstack Glance with Webob 1.1.1 as found in Ubuntu 12.04+

Taking the following code from glance:

``` python
    def download(self, response, result):
        size = result['meta']['size']
        checksum = result['meta']['checksum']
        response.headers['Content-Length'] = size
        response.headers['Content-Type'] = 'application/octet-stream'
        if checksum:
            response.headers['Content-MD5'] = checksum
        response.app_iter = common.size_checked_iter(
                response, result['meta'], size, result['data'], self.notifier)
```

This should create a response with appropriate headers (including a MD5 checksum) and then use the iterator to return the content (potentially a large image) to the calling client; however when:

``` python
 response.app_iter = ...
```

occurs the MD5 that was set in the preceeding line is set back to 'None' in the response object; result is a chunked transfer encoded response without a checksum (which should be supported). I traced this back to webob/response.py:

``` python
    def _app_iter__set(self, value):
        if self._app_iter is not None:
            # Undo the automatically-set content-length
            self.content_length = None
            self.content_md5 = None
        self._app_iter = value
```

During construction of the object, neither the app_iter or body is specified and as a result the body is set to '' (and the app_iter to [ '' ]). So even though no data has ever been provided, the md5 sum is dropped as soon as the iterator is provided.

Switching the order of the code fixes the problem; but the handling of resetting the md5 does feel odd.

``` python
    def download(self, response, result):
        size = result['meta']['size']
        checksum = result['meta']['checksum']
        response.headers['Content-Length'] = size
        response.headers['Content-Type'] = 'application/octet-stream'
        response.app_iter = common.size_checked_iter(
                response, result['meta'], size, result['data'], self.notifier)
        if checksum:
            response.headers['Content-MD5'] = checksum
```

**Comment by sigmavirus24** [comment]
So, RFC 2616 has been updated and reified into RFCs 7230-7235. Content-MD5 has been removed from the definition per [7231 Appendix B](https://tools.ietf.org/html/rfc7231#appendix-B) which says

```
   The Content-MD5 header field has been removed because it was
   inconsistently implemented with respect to partial responses.
```

That said, if we look at [2616 §14.15](https://tools.ietf.org/html/rfc2616#section-14.15) we see that there's nothing prohibiting combining a chunked transfer-encoding with content-md5 (as @saschpe pointed out) and to just be extra clear

```
   The MD5 digest is computed based on the content of the entity-body,
   including any content-coding that has been applied, but not including
   any transfer-encoding applied to the message-body. If the message is
   received with a transfer-encoding, that encoding MUST be removed
   prior to checking the Content-MD5 value against the received entity.
```

The Content-MD5 must be calculated *after* removing any Transfer-Encoding.

@bertjwregeer I suspect that since this is still open that you'd be open to me sending a fix, yes?

**Comment by bertjwregeer** [comment]
@sigmavirus24 I am open to any and all fixes to fix bugs in WebOb :-). This is still open because I am not sure what the best way to fix this issue is.

I did open another ticket: https://github.com/Pylons/webob/issues/272 that is to add explicit get/set data methods that can do a bunch more magic based upon arguments/keyword arguments past in rather than having to infer what is needed based upon a property being set.

Ultimately if a newer RFC removes Content-MD5, I would like to deprecate Content-MD5 in WebOb eventually. Is there a replacement that is better?

**Comment by sigmavirus24** [comment]
@bertjwregeer so many services are going to heavily depend on Content-MD5 as an integrity check.

To be clear, the updates made to 2616 in 7230, 7231, 7232, 7233, 7234, and 7235 were to reflect the current state and best practices around HTTP/1.1. There was no way to define the current state or best current practice around Content-MD5 (I suspect) and so to avoid having the RFC in conflict with many existing implementations, they removed it. I don't think that means that it's an invalid header or something WebOb should stop using though.

If WebOb were a greenfield framework, I'd say "Yes, don't add support for generating Content-MD5" but I'd also advise you not to strip it when the user specifies it.

Also, I've been reading [3230](https://tools.ietf.org/html/rfc3230) as this defines the [`Digest`](https://tools.ietf.org/html/rfc3230#section-4.3.2) and [`Want-Digest`](https://tools.ietf.org/html/rfc3230#section-4.3.1) headers.

To recapitulate though:

- This bug is about the fact that WebOb strips the `Content-MD5` header that Glance provides
- We should open a separate bug for adding `Want-Digest` negotiation (if that's something WebOb wants to support, I've not seen it widely used but the best way to encourage something's usage is to make it easy to use)
- We should open a separate discussion as to whether or not WebOb should auto-generate `Content-MD5` headers for users.

**Comment by bertjwregeer** [comment]
Deprecate means not automatically generate it, I would still keep support for it, I wouldn't remove it entirely.

AFAIK there are currently a couple of different code paths that touch the Content-MD5 header, I'd want to pull as much of that out as possible.

**Comment by bertjwregeer** [comment]
`Want-Digest` looks like it's going to be as fun to implement as `Accept` and friends ;-)
